### ISSUE TITLE
Tests are failing by default

### ISSUE THREAD

**Issue by NiclRich** [FAIRmat-NFDI/nomad-plugin-template#5]
Hi everyone,

I'm trying to develop a plugin using this template. I followed the instructions of the README and tried to run the tests. Those failed however and yielded the following error:

```
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.2, pluggy-1.5.0 -- /home/###/###/nomad-example/testplugin/bin/python3
cachedir: .pytest_cache
rootdir: /home/###/###/nomad-example/testplugin
configfile: pyproject.toml
plugins: anyio-4.4.0
collected 3 items / 1 error                                                    

==================================== ERRORS ====================================
________________ ERROR collecting tests/parsers/test_parser.py _________________
ImportError while importing test module '/home/###/###/nomad-example/testplugin/tests/parsers/test_parser.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/parsers/test_parser.py:4: in <module>
    from nomad_foobar.parsers.myparser import MyParser
E   ModuleNotFoundError: No module named 'nomad_foobar'

```

The system I used is Linux with the latest PopOS! distro. The ### are inserted by me, since it contains personal information about me.

Can somebody help me to resolve this issue? Thanks in advance.

**Comment by blueraft** [comment]
Hi.

The error suggests to me that the package may not have been installed.

Are you in the correct virtual env where you ran the pip install command?

**Comment by NiclRich** [comment]
To which package do you refer? I installed nomad-lab Version 1.2.1, which is the newest available through PyPi. Furthermore, I created the virtual environment with the Python Module venv and executed the cruft command afterwards. The necessary packages are all installed in the virtual environment.

**Comment by blueraft** [comment]
`nomad_foobar`.

The last step described [here](https://github.com/FAIRmat-NFDI/nomad-polymerization-reactions?tab=readme-ov-file#install).

Could you share the `.cruft.json`file? I can try to reproduce it locally then

**Comment by NiclRich** [comment]
I installed the newest version as described in your link and now it works. So this issue can be closed. Thank you very much!
